[project]
name = "ckanext-lakehouse_theme"
version = "0.0.1"
description = "Theme cho CKAN data portal cua Lakehouse"
readme = "README.md"
authors = [
    {name = "jayyyyte"}
]
license = {text = "AGPL"}
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

keywords = [ "CKAN", "theme", "lakehouse", ]
dependencies = []

[project.urls]
Homepage = "https://github.com/jayyyyte/ckanext-lakehouse_theme"

[project.entry-points."ckan.plugins"]
lakehouse_theme = "ckanext.lakehouse_theme.plugin:LakehouseThemePlugin"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
        "ignore::sqlalchemy.exc.SADeprecationWarning",
        "ignore::sqlalchemy.exc.SAWarning",
        "ignore::DeprecationWarning",
]
addopts = "--ckan-ini test.ini"

[tool.ruff]
line-length = 127

[tool.ruff.lint]
select = ["E", "F", "W"]

